stage: 'eval'
model_path: 'bert-base-uncased'
train_file: 'all_data_train.jsonl'
valid_file: 'all_data_valid.jsonl'
test_file: 'all_data_test.jsonl'
labels_file: 'labels.json'
num_workers: 0
max_len: 256
lr: 0.001
batch_size: 64
exp_name: 'nlu_final'
save_top_k: 2
refresh_rate: 1
n_gpus: 1
n_epochs: 0
num_sanity_val_steps: 0
seed: 777