exp_name: 'nlu_simple'
seed: 777
data_module:
  
  train_file: 'all_data_train_simple.jsonl'
  valid_file: 'all_data_valid_simple.jsonl'
  test_file: 'all_data_test_simple.jsonl'
  labels_file: 'labels_simple.json'
  num_workers: 0
  max_len: 256
  batch_size: 64

model:
  stage: 'eval'
  model_path: 'bert-base-uncased'
  lr: 0  # set to 0 if use CosineAnnealingWarmUpRestarts
  weight_decay_rate: 0.00001
  loss_type: 'focal' # focal / ce
  focal:
    alpha: 1
    gamma: 300
  schedular:
    T_0: 3
    T_up: 1
    T_mult: 1
    eta_max: 0.01
    gamma: 0.75

trainer:
  save_top_k: 2
  refresh_rate: 1
  n_epochs: 10
  n_gpus: 1
  num_sanity_val_steps: 0