exp_name: 'nlu_simple'
seed: 1234
data_module:  
  train_file: 'all_data_test_simple_l7_tk3_3.jsonl'
  valid_file: 'all_data_valid_simple_l7_tk3_3.jsonl'
  test_file: 'all_data_test_simple_l7_tk3_3.jsonl'
  labels_file: 'labels_simple.json'
  num_workers: 0
  max_len: 256
  batch_size: 64

model:
  stage: 'train'
  model_path: 'bert-base-uncased'
  weight_file: 'all_data_count_l7_tk3_0.json'
  lr: 0.0  # set to 0 if use CosineAnnealingWarmUpRestarts
  weight_decay_rate: 0.01
  loss_type: 'focal' # focal / ce
  optim: 
    type: 'AdamW'  # Adam / AdamW
    eps: 0.8
  focal:
    alpha: 0.95
    gamma: 3
  schedular:
    type: 'cosine_with_restarts' # 'cosine', 'cosine_with_restarts' / # 'linear', 'polynomial', 'constant', 'constant_with_warmup'
    num_cycles : 3
    warmup_steps: 250

trainer:
  save_top_k: 2
  refresh_rate: 1
  n_epochs: 12
  n_gpus: 1
  num_sanity_val_steps: 0
  strategy: 'ddp_spawn'  #  dp | ddp | ddp2 | ddp_spawn
  log_every_n_steps: 25
  deterministic: false
  gradient_clip_val: 0.0