stage: 'train'
model_path: 'bert-base-uncased'
data_file: 'all_data_splitted.pickle'
ids_file: 'all_data_ids.pickle'
num_workers: 0
test_size: 0.1
max_len: 64
lr: 0.001
batch_size: 64
exp_name: 'nlu'
save_top_k: 2
refresh_rate: 1
n_gpus: 1
n_epochs: 20
num_sanity_val_steps: 0
seed: 777