ontology:
  graph_drawer:
    height: '800px' 
    width: '100%' 
    directed: true 
    font_color: 'black' 
    heading: '' 
    notebook: true
    show_file_name: 'nx.html'

db:
  dbname: 'fsqa'
  host: 'localhost'
  user: 'postgres'
  password: ''
  port: 5432