ontology:
  graph_drawer:
    height: '600px' 
    width: '100%' 
    directed: true 
    font_color: 'black' 
    heading: '' 
    notebook: true
    show_file_name: 'nx.html'
  model:
    model_name: 'linear_model.pickle'

db:
  dbname: 'fsqa'
  host: 'localhost'
  user: 'postgres'
  password: ''
  port: 5432